/* 
 *  Copyright 2022 VMware, Inc.
 *  
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/vmware-tanzu/service-instance-migrator-for-cloud-foundry/pkg/cmd"
	"github.com/vmware-tanzu/service-instance-migrator-for-cloud-foundry/pkg/config"
)

type FakeSpaceExporter struct {
	ExportStub        func(context.Context, config.OpsManager, string, string, string) error
	exportMutex       sync.RWMutex
	exportArgsForCall []struct {
		arg1 context.Context
		arg2 config.OpsManager
		arg3 string
		arg4 string
		arg5 string
	}
	exportReturns struct {
		result1 error
	}
	exportReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSpaceExporter) Export(arg1 context.Context, arg2 config.OpsManager, arg3 string, arg4 string, arg5 string) error {
	fake.exportMutex.Lock()
	ret, specificReturn := fake.exportReturnsOnCall[len(fake.exportArgsForCall)]
	fake.exportArgsForCall = append(fake.exportArgsForCall, struct {
		arg1 context.Context
		arg2 config.OpsManager
		arg3 string
		arg4 string
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ExportStub
	fakeReturns := fake.exportReturns
	fake.recordInvocation("Export", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.exportMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSpaceExporter) ExportCallCount() int {
	fake.exportMutex.RLock()
	defer fake.exportMutex.RUnlock()
	return len(fake.exportArgsForCall)
}

func (fake *FakeSpaceExporter) ExportCalls(stub func(context.Context, config.OpsManager, string, string, string) error) {
	fake.exportMutex.Lock()
	defer fake.exportMutex.Unlock()
	fake.ExportStub = stub
}

func (fake *FakeSpaceExporter) ExportArgsForCall(i int) (context.Context, config.OpsManager, string, string, string) {
	fake.exportMutex.RLock()
	defer fake.exportMutex.RUnlock()
	argsForCall := fake.exportArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeSpaceExporter) ExportReturns(result1 error) {
	fake.exportMutex.Lock()
	defer fake.exportMutex.Unlock()
	fake.ExportStub = nil
	fake.exportReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSpaceExporter) ExportReturnsOnCall(i int, result1 error) {
	fake.exportMutex.Lock()
	defer fake.exportMutex.Unlock()
	fake.ExportStub = nil
	if fake.exportReturnsOnCall == nil {
		fake.exportReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.exportReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSpaceExporter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.exportMutex.RLock()
	defer fake.exportMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSpaceExporter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cmd.SpaceExporter = new(FakeSpaceExporter)
