/* 
 *  Copyright 2022 VMware, Inc.
 *  
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/vmware-tanzu/service-instance-migrator-for-cloud-foundry/pkg/cf"
	"github.com/vmware-tanzu/service-instance-migrator-for-cloud-foundry/pkg/config"
	"github.com/vmware-tanzu/service-instance-migrator-for-cloud-foundry/pkg/migrate"
)

type FakeMigratorRegistry struct {
	LookupStub        func(string, string, *cf.ServiceInstance, config.OpsManager, string, bool) (migrate.ServiceInstanceMigrator, bool, error)
	lookupMutex       sync.RWMutex
	lookupArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 *cf.ServiceInstance
		arg4 config.OpsManager
		arg5 string
		arg6 bool
	}
	lookupReturns struct {
		result1 migrate.ServiceInstanceMigrator
		result2 bool
		result3 error
	}
	lookupReturnsOnCall map[int]struct {
		result1 migrate.ServiceInstanceMigrator
		result2 bool
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMigratorRegistry) Lookup(arg1 string, arg2 string, arg3 *cf.ServiceInstance, arg4 config.OpsManager, arg5 string, arg6 bool) (migrate.ServiceInstanceMigrator, bool, error) {
	fake.lookupMutex.Lock()
	ret, specificReturn := fake.lookupReturnsOnCall[len(fake.lookupArgsForCall)]
	fake.lookupArgsForCall = append(fake.lookupArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 *cf.ServiceInstance
		arg4 config.OpsManager
		arg5 string
		arg6 bool
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	stub := fake.LookupStub
	fakeReturns := fake.lookupReturns
	fake.recordInvocation("Lookup", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.lookupMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeMigratorRegistry) LookupCallCount() int {
	fake.lookupMutex.RLock()
	defer fake.lookupMutex.RUnlock()
	return len(fake.lookupArgsForCall)
}

func (fake *FakeMigratorRegistry) LookupCalls(stub func(string, string, *cf.ServiceInstance, config.OpsManager, string, bool) (migrate.ServiceInstanceMigrator, bool, error)) {
	fake.lookupMutex.Lock()
	defer fake.lookupMutex.Unlock()
	fake.LookupStub = stub
}

func (fake *FakeMigratorRegistry) LookupArgsForCall(i int) (string, string, *cf.ServiceInstance, config.OpsManager, string, bool) {
	fake.lookupMutex.RLock()
	defer fake.lookupMutex.RUnlock()
	argsForCall := fake.lookupArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *FakeMigratorRegistry) LookupReturns(result1 migrate.ServiceInstanceMigrator, result2 bool, result3 error) {
	fake.lookupMutex.Lock()
	defer fake.lookupMutex.Unlock()
	fake.LookupStub = nil
	fake.lookupReturns = struct {
		result1 migrate.ServiceInstanceMigrator
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeMigratorRegistry) LookupReturnsOnCall(i int, result1 migrate.ServiceInstanceMigrator, result2 bool, result3 error) {
	fake.lookupMutex.Lock()
	defer fake.lookupMutex.Unlock()
	fake.LookupStub = nil
	if fake.lookupReturnsOnCall == nil {
		fake.lookupReturnsOnCall = make(map[int]struct {
			result1 migrate.ServiceInstanceMigrator
			result2 bool
			result3 error
		})
	}
	fake.lookupReturnsOnCall[i] = struct {
		result1 migrate.ServiceInstanceMigrator
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeMigratorRegistry) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.lookupMutex.RLock()
	defer fake.lookupMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMigratorRegistry) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ migrate.MigratorRegistry = new(FakeMigratorRegistry)
